[general]
initial-tool = "arrow"

[color-palette]
palette = [
    "#ff0000",
    "#00ff00",
    "#0000ff",
    "#ffff00",
    "#ff00ff",
    "#00ffff"
]

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "a"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "h"
